services:
  app:
    build: .
    container_name: script-logica
    depends_on:
      - db
    networks:
      - dev-net
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql-devops
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: devops_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dev-net
  backup:
    build: ./backup-service
    depends_on:
      - db
    volumes:
      - ./respaldo:/respaldo
    networks:
      - dev-net

  app-python:
    build: ./app-python
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
      MYSQL_DATABASE: devops_db
    networks:
      - dev-net
    ports:
      - "5001:5000"

volumes:
  mysql-data:

networks:
  dev-net:
    driver: bridge
