version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-devops
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gestion_vehicular
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    container_name: app-python
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      MYSQLHOST: mysql
      MYSQLUSER: admin
      MYSQLPASSWORD: adminpass
      MYSQLDATABASE: gestion_vehicular
      MYSQLPORT: 3306

volumes:
  dbdata: