version: '3.8'

services:
  app:
    build: .
    container_name: script-logica
    depends_on:
      - db
    tty: true  # permite entrada interactiva
    stdin_open: true

  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql-devops
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: devops_db
    ports:
      - "3306:3306"
