services:
  - type: web
    name: api-devops
    env: docker
    repo: https://github.com/yuchag94/devops-bootcamp
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "python app.py"
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: MYSQL_HOST
        value: tu-host-remoto
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: rootpass
      - key: MYSQL_DATABASE
        value: devops_db
