services:
  - type: web
    name: api-devops
    env: docker
    repo: https://github.com/yuchag94/devops-bootcamp
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "python app.py"
    healthCheckPath: /
    envVars:
      - key: MYSQLHOST
        value: mysql://root:JdZwbqFXBnbKusRBbkVZPsDcqMUPFKQl@yamabiko.proxy.rlwy.net:30531/railway
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        value: yLaNXNWGkUGayEvHDtQEmdOjfvLcRqpL
      - key: MYSQLDATABASE
        value: gestion_vehicular
      - key: MYSQLPORT
        value: "59274"
