services:
  - type: web
    name: api-devops
    env: docker
    repo: https://github.com/yuchag94/devops-bootcamp
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "python app.py"
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: MYSQL_HOST
        value: mysql://root:yLaNXNWGkUGayEvHDtQEmdOjfvLcRqpL@tramway.proxy.rlwy.net:59274/railway
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: yLaNXNWGkUGayEvHDtQEmdOjfvLcRqpL
      - key: MYSQL_DATABASE
        value: gestion_vehicular
      - key: MYSQL_PORT
        value: "59274"
