services:
  - type: web
    name: api-devops
    env: docker
    repo: https://github.com/yuchag94/devops-bootcamp
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "python app.py"
    healthCheckPath: /
    envVars:
      - key: MYSQLHOST
        value: yamabiko.proxy.rlwy.net
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        value: JdZwbqFXBnbKusRBbkVZPsDcqMUPFKQl
      - key: MYSQLDATABASE
        value: railway
      - key: MYSQLPORT
        value: "30531"
